services:
  app:
    image: openjdk:17-jdk-slim
    container_name: spring-graphql-app
    working_dir: /app
    depends_on:
      - zipkin
    volumes:
      - ./bookInfo/build/libs/bookInfo-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    command: ["java", "-jar", "app.jar"]
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
